- name: Copy backend files
  become: true
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: "Unzip backend files to correct directory"
  shell: |
    cd /home/ubuntu/
    tar -xvzf artifact.tar.gz
    
- name: "Install dependencies for project and start app"
  shell: |
    npm install

- name: "Start backend app"
  shell: |
    pm2 start npm -- run start