- name: "Unzip backend files to correct directory"
  shell: |
    cd ~/backend
    tar -xvzf artifact.tar.gz
    echo 'hereeeee'
    
- name: "Install dependencies for project and start app"
  shell: |
    cd ~/backend
    npm install

- name: "Start backend app"
  shell: |
    cd ~/backend
    pm2 stop default
    pm2 start npm -- start